void copytree() {
// Example of Root macro to copy a subset of a Tree to a new Tree
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 1 1
//Author: Rene Brun
   
   gSystem->Load("$ROOTSYS/test/libEvent");

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile("/home/samantha/samantha/05032013_StopNtuples/MG_QCD_HT_500To1000/6282_169.root");
   TTree *oldtree = (TTree*)oldfile->Get("treeMaker/tree");
   oldtree->SetBranchStatus("*",0);
   oldtree->SetBranchStatus("t_EvtRun",1);
   oldtree->SetBranchStatus("t_EvtLS",1);
   oldtree->SetBranchStatus("t_EvtEvent",1);

   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile("small.root","recreate");
   TTree *newtree = oldtree->CloneTree();

   newtree->Print();
   newfile->Write();
   delete oldfile;
   delete newfile;
}
